### PR TITLE
Meshrdf klortho

### PR DESCRIPTION
**Pull request by Klortho**
The changers here are mostly for [mesh-rdf#130](https://github.com/HHS/mesh-rdf/issues/130). You can check them out at http://iddev.nlm.nih.gov/klortho.  Here are some highlights:

* Error messages now stand out more.  E.g. [here](http://iddev.nlm.nih.gov/klortho/sparql?query=PRE&render=HTML&year=current&limit=50&offset=0#lodestart-sparql-results)
* Queries against the "latest year" (e.g. 2015, as opposed to the "current") work; e.g. [here](http://iddev.nlm.nih.gov/klortho/sparql?query=PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0D%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0D%0APREFIX+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0D%0APREFIX+meshv%3A+%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2Fvocab%23%3E%0D%0APREFIX+mesh%3A+%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2F%3E%0D%0APREFIX+mesh2015%3A+%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2F2015%2F%3E%0D%0A%0D%0ASELECT+*+%0D%0AFROM+%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2F2015%3E%0D%0AWHERE+%7B%0D%0A++mesh2015%3AD015242+meshv%3ApharmacologicalAction+%3Fpa+.%0D%0A++%3Fpa+rdfs%3Alabel+%3FpaLabel+.%0D%0A%7D+%0D%0A&render=HTML&year=2015&limit=50&offset=0#lodestart-sparql-results)
* URIs with the year will now resolve.  For example, [http://id.nlm.nih.gov/mesh/2015/D065609](http://iddev.nlm.nih.gov/klortho/2015/D065609).  These should work in all the various output formats (REST interface).
* The [SPARQL page](http://iddev.nlm.nih.gov/klortho/sparql) now has a "year" control, to let you switch the currently displayed query between "latest" and "current".

### CODE REVIEW

**Comment by danizen** [comment]
This all looks good to me on a cursory glance.   I'm looking mostly to learn how the redirect filter works, anyway, and how lodestar.js is put together I need to study from scratch - this helps only a little.   One question I had is about using the same meshv: predicate in both graph `<http://id.nlm.nih.gov/mesh/>` and graph `<http://id.nlm.nih.gov/mesh/2015>`.    Should we load only the one graph for the vocabulary or do we load the same `vocabulary.ttl` in both graphs? Won't that breakdown if we are concurrently hosting MeSH 2016 and MeSH 2015?

**Comment by Klortho** [comment]
Most of the URL handling is controlled by urlrewrite.xml, and I started to try to make a thorough survey of all of them [here](https://docs.google.com/drawings/d/1YukvDdi1NlQSiq9hS0bWQXA2UmqjWeBrSraV8C6Nzmw/edit).

[Issue 47](https://github.com/HHS/mesh-rdf/issues/47) is about getting all of them finished.  What would be ideal is if we could turn that google doc into a YAML file, and use it for the basis of automated testing.  What do you think?

lode.js is a bit messy -- could definitely use some refactoring.

**Comment by Klortho** [comment]
> Should we load only the one graph for the vocabulary or do we load the same vocabulary.ttl in both graphs?

See [here in the Versioning page](https://wiki.nlm.nih.gov/confluence/display/LD/Versioning#Versioning-VirtuosoandLodestarimplementation)

We're only loading the vocabulary to one graph -- its own.  One Virtuoso/lodestar instance has one and only one rule set to use for inferencing.  Both "current" and "latest" use that, so it works pretty well.

I guess, when it's time for the 2016 switchover, we'll need another Virtuoso/lodestar instance, that will serve the 2015 data, while the existing one switches to serving current and latest (2016).

**Comment by danizen** [comment]
> What would be ideal is if we could turn that google doc into a YAML file, and use it for the basis of 
> automated testing. What do you think?

You could get from Google Docs to a CSV easily enough.   I'm not sure what I think about YAML.   CSV would work well enough I suspect.

**Comment by Klortho** [comment]
You love YAML, you just don't know it yet!  ;)

**Comment by danizen** [comment]
> You love YAML, you just don't know it yet!  ;)

SOAP was taken to be the RPC to rule them all.  NFS and COM have strangely not gone away.  Similarly, markdown and YAML.   I love YAML, but CSV is easier to back and forth from a spreadsheet.   You have tabular data - why it's in an image is a bit beyond me.   A google doc that is a spreadsheet would be better.

**Comment by Klortho** [comment]
> A google doc that is a spreadsheet would be better.

I couldn't get it to behave the way I wanted -- spent way too much time on formatting.

**Pull request merged**
